spring.application.name=message_expense_checker
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=sms_expense_checker
spring.batch.job.enabled=false
spring.autoconfigure.exclude = org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
spring.data.mongodb.uri=mongodb://localhost:27017/sms_expense_checker

spring.main.allow-bean-definition-overriding=true

# spring.web.application.path=/smsChecker
